apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-dev
  namespace: argocd
spec:
  description: dev Project

  sourceRepos:
    - https://github.com/mohamed1311990/nodejs.git

  destinations:
    - namespace: dev-*
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment

    - group: ""
      kind: Service
